# Generated by Django 4.2.7 on 2023-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('tel', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('genero', models.CharField(choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
