# Generated by Django 4.2.7 on 2023-11-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='genero',
            new_name='género',
        ),
    ]
