# Generated by Django 4.2.7 on 2023-11-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_servicio_habitación'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
    ]
