# Generated by Django 4.2.7 on 2023-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0006_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('C', 'Tarjeta'), ('E', 'Efectivo'), ('T', 'Tranferencia')], max_length=1),
        ),
    ]
