# Generated by Django 4.2.7 on 2023-12-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0007_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_habitación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='habitación',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP1.tipo_habitación'),
        ),
    ]
