# Generated by Django 4.2.7 on 2023-12-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0008_tipo_habitación_alter_habitación_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_habitación',
            options={'verbose_name': 'tipoH', 'verbose_name_plural': 'Tipos de Habitaciones'},
        ),
        migrations.AlterModelTable(
            name='tipo_habitación',
            table='tipo_habitación',
        ),
    ]
