# Generated by Django 4.2.7 on 2023-12-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0009_alter_tipo_habitación_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitación',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
