# Generated by Django 4.2.7 on 2023-12-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0010_habitación_ocupada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
