# Generated by Django 4.2.7 on 2023-12-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0011_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='habitación',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='APP1.habitación'),
        ),
    ]
